### ISSUE TITLE
Rework GetRange to use batch-suspendable system from DMQ Consume

### ISSUE THREAD

**Issue by gavin-norman-sociomantic** [sociomantic-tsunami/dlsproto#7]
sociomantic-tsunami/dmqproto#3 discusses a (hopefully) much simpler and more reliable way of implementing a suspendable request. If the reworking of Consume is successful, GetAll should be reworked in the same way.

**Comment by gavin-norman-sociomantic** [comment]
Is this done?

**Comment by nemanja-boric-sociomantic** [comment]
Yes.
